In [1]:
import pandas as pd
import numpy as np
import scipy as sp

In [2]:
#Imported data from midterm
#Top 100 ultra marathons within the United states from 1963 to 2022.

um_df = pd.read_csv("../Data/UM_data_top_100.csv")

In [3]:
# Dropped the unnamed column.
um_df = um_df.drop(columns=['Unnamed: 0'])

In [4]:
# Virginia was missing from state codes column, added it.
um_df['state_code'].fillna('VA', inplace=True)

/var/folders/_4/_j38q0cn0kg4pnd1jf3yvymr0000gn/T/ipykernel_3206/3303835124.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  um_df['state_code'].fillna('VA', inplace=True)

In [5]:
# Adding Latitude and Longitude of races

latitude = {'JFK 50 Mile (USA)': 39.5019,
            'American River 50 Mile Endurance Run (USA)': 38.6742,
            'Way Too Cool 50K Endurance Run (USA)': 38.7419,
            'Western States 100 Mile Endurance Run (USA)': 39.3133,
            'Rachel Carson Trail Challenge (USA)': 40.6526,
            'Leadville Trail 100 Mile (USA)': 39.2444,
            'The HAT Run 50K (USA)': 39.5763,
            'Sunmart Texas Trail Endurance Run 50 Km (USA)': 30.7283,
            'Quad Dipsea Trail Run (USA)': 37.8942,
            'Skyline 50k Endurance Run (USA)': 37.6786,
            'Bull Run Run 50 Miler (USA)': 38.7600,
            'Mountain Mist 50k (USA)': 34.7300,
            'Chuckanut 50K (USA)': 48.7033,
            'Mountain Masochist 50 Mile Trail Run (USA)': 37.5700,
            'Ice Age Trail 50 Mile Run (USA)': 42.8217,
            'Vermont 100 Mile Endurance Race (USA)': 43.6050,
            'Promise Land 50K++ (USA)': 37.2333,
            'Huff 50K Trail Run (USA)': 41.2300,
            'Squaw Peak 50 Mile Trail Run (USA)': 40.2583,
            'Wasatch Front 100 Mile (USA)': 41.0275,
            'Holiday Lake 50K++ (USA)': 37.3450,
            'NYRR Knickerbocker 60K (USA)': 40.7820,
            'Avalon Benefit 50-Mile Run (USA)': 33.3511,
            'OTHTC High Desert 50K Ultra (USA)': 35.6350,
            'McDonald Forest 50K Trail Run (USA)': 44.5760,
            'Leadville Silver Rush 50 Mile Run (USA)': 39.2444,
            'Rock/Creek StumpJump 50K (USA)': 35.0483,
            'Minnesota Voyageur Trail 50 Mile Ultra (USA)': 46.6651,
            'Rocky Raccoon 100 Mile Trail Run (USA)': 30.7283,
            'Dick Collins Firetrails 50 Mile (USA)': 37.6786,
            'Crown King Scramble 50K (USA)': 33.8544,
            'Bulldog 50k Ultra Run (USA)': 34.0683,
            'Endurance Challenge - California Trail 50 km (USA)': 37.8072,
            'Endurance Challenge - California Trail 50 Mile (USA)': 37.8200,
            'Endurance Challenge - Washington D.C. Trail 50 km (USA)': 38.9694,
            'White River 50 Mile Trail Run (USA)': 47.2525,
            'Javelina Jundred 100 Mile Endurance Run (USA)': 33.6267,
            'Strolling Jim 40 Mile (USA)': 35.5800,
            'Leona Divide 50 Mile Run (USA)': 34.7033,
            'Blues Cruise 50K Ultra Trail (USA)': 40.3340,
            'The Cowtown Marathon (USA)': 32.7510,
            'Endurance Challenge - New York Trail 50 km (USA)': 41.3133,
            'Afton Trail Run 50K (USA)': 44.9783,
            'Golden Gate Dirty 30 (USA)': 39.7700,
            'Shadow of the Giants 50K (USA)': 36.7811,
            'Vermont 50 Miles Ultra Run (USA)': 43.4510,
            'Quicksilver 50 km Endurance Run (USA)': 37.2230,
            'Bighorn Mountain Wild & Scenic 50km Trail Run (USA)': 44.8733,
            'Ohlone 50K Wilderness Run (USA)': 37.4850,
            'Miwok 100k Trail race (USA)': 37.9011,
            'Siskiyou Out Back 50 km Trail Run (USA)': 42.0544,
            'The Rut Mountain Runs (USA)': 45.2844,
            'Sylamore Trail 50k Run (USA)': 35.7917,
            'Tamalpa Headlands 50K (USA)': 37.8725,
            'Speedgoat 50k (USA)': 40.5961,
            'Moab Red Hot 55k (USA)': 38.6325,
            'McKenzie River 50 km Trail Run (USA)': 44.1230,
            'San Juan Solstice 50 Mile Run (USA)': 38.0250,
            'Chicago Lakefront Fall 50K (USA)': 41.9990,
            'Lake Sonoma 50 Mile Race (USA)': 38.6730,
            'The Bear 100 Mile Endurance Run (USA)': 41.7370,
            'Mount Cheaha 50K UltraMarathon Race (USA)': 33.9700,
            'Vermont 50 km Ultra Run (USA)': 43.4510,
            'Stone Mill 50 Mile Run (USA)': 39.1360,
            'Black Canyon Trail 100 Km Run (USA)': 34.4300,
            'Angeles Crest 100 Mile (USA)': 34.3750,
            'Ice Age Trail 50 km Run (USA)': 42.8217,
            'Umstead Endurance Run 100 Miles (USA)': 35.8200,
            'Tunnel Hill 50 Mile Race (USA)': 38.9970,
            'Catoctin 50k Trail Run (USA)': 39.6400,
            'Jed Smith Ultra Classic - 50 Km Race (USA)': 35.5647,
            'Highlands Sky 40M Trail Run (USA)': 38.8720,
            'Sunmart Texas Trail Endurance Run 50 Mile (USA)': 30.7280,
            'Noble Canyon 50k (USA)': 33.2350,
            'Hagg Lake Trail Runs 50K (USA)': 42.3520,
            'Endurance Challenge - New York Trail 50 Miles (USA)': 41.3130,
            'Terrapin Mountain 50k (USA)': 37.5550,
            'Massanutten Mountain Trails 100 Mile (USA)': 38.7900,
            'Mount Mitchell Challenge (USA)': 35.6110,
            'Le Grizz 50 Mile Ultramarathon (USA)': 48.8560,
            'Arkansas Traveller 100 (USA)': 34.8980,
            'Umstead Endurance Run 50 Miles (USA)': 35.8200,
            'Pineland Farms 50 km Trail Running (USA)': 43.9700,
            'Buckeye Trail 50k (USA)': 41.3100,
            'Endurance Challenge - Washington D.C. Trail 50 Miles (USA)': 41.3130,
            'Salem Lakeshore Frosty Fifty (USA)': 36.0700,
            'Marine Corps 50km Marathon Race (USA)': 38.8700,
            'Orcas Island 50k (USA)': 48.6500,
            'Endurance Challenge - Wisconsin Trail 50 km (USA)': 43.0630,
            'Holcomb Valley 33 Mile (USA)': 34.2600,
            'Mohican Trail 100 Mile (USA)': 40.6010,
            'Bighorn Mountain Wild & Scenic 50mi Trail Run (USA)': 44.4170,
            'Baker Lake 50K Ultra Trail Run (USA)': 48.8500,
            'Chippewa Moraine 50km Ultra Marathon (USA)': 45.0100,
            'Superior Spring 50 km Trail Race (USA)': 47.7000,
            'Trail Mix Race (USA)': 40.6100,
            'Capon Valley 50K Run (USA)': 39.3667,
            'Chicago Lakefront Spring 50K (USA)': 41.7650,
            'Hardrock Hundred Endurance Run (USA)': 37.7900,
            'Burning River 100 Mile Endurance Run (USA)': 41.1330} 

longitude = {'JFK 50 Mile (USA)': -77.6631,
             'American River 50 Mile Endurance Run (USA)': -121.1694,
             'Way Too Cool 50K Endurance Run (USA)': -120.5678,
             'Western States 100 Mile Endurance Run (USA)': -120.2300,
             'Rachel Carson Trail Challenge (USA)': -79.6998,
             'Leadville Trail 100 Mile (USA)': -106.3194,
             'The HAT Run 50K (USA)': -76.0856,
             'Sunmart Texas Trail Endurance Run 50 Km (USA)': -95.5500,
             'Quad Dipsea Trail Run (USA)': -122.5456,
             'Skyline 50k Endurance Run (USA)': -122.0883,
             'Bull Run Run 50 Miler (USA)': -77.4267,
             'Mountain Mist 50k (USA)': -86.5883,
             'Chuckanut 50K (USA)': -122.4786,
             'Mountain Masochist 50 Mile Trail Run (USA)': -79.4500,
             'Ice Age Trail 50 Mile Run (USA)': -88.6004,
             'Vermont 100 Mile Endurance Race (USA)': -72.5794,
             'Promise Land 50K++ (USA)': -79.4667,
             'Huff 50K Trail Run (USA)': -85.2283,
             'Squaw Peak 50 Mile Trail Run (USA)': -111.6458,
             'Wasatch Front 100 Mile (USA)': -111.8667,
             'Holiday Lake 50K++ (USA)': -78.8033,
             'NYRR Knickerbocker 60K (USA)': -73.9654,
             'Avalon Benefit 50-Mile Run (USA)': -118.3278,
             'OTHTC High Desert 50K Ultra (USA)': -117.6372,
             'McDonald Forest 50K Trail Run (USA)': -123.2620,
             'Leadville Silver Rush 50 Mile Run (USA)': -106.3194,
             'Rock/Creek StumpJump 50K (USA)': -85.3528,
             'Minnesota Voyageur Trail 50 Mile Ultra (USA)': -92.4227,
             'Rocky Raccoon 100 Mile Trail Run (USA)': -95.5500,
             'Dick Collins Firetrails 50 Mile (USA)': -122.0883,
             'Crown King Scramble 50K (USA)': -112.4083,
             'Bulldog 50k Ultra Run (USA)': -118.6436,
             'Endurance Challenge - California Trail 50 km (USA)': -122.4267,
             'Endurance Challenge - California Trail 50 Mile (USA)': -122.5000,
             'Endurance Challenge - Washington D.C. Trail 50 km (USA)': -77.3178,
             'White River 50 Mile Trail Run (USA)': -121.6425,
             'Javelina Jundred 100 Mile Endurance Run (USA)': -111.7375,
             'Strolling Jim 40 Mile (USA)': -86.3100,
             'Leona Divide 50 Mile Run (USA)': -118.3450,
             'Blues Cruise 50K Ultra Trail (USA)': -75.9250,
             'The Cowtown Marathon (USA)': -97.3300,
             'Endurance Challenge - New York Trail 50 km (USA)': -74.0022,
             'Afton Trail Run 50K (USA)': -92.8394,
             'Golden Gate Dirty 30 (USA)': -105.5420,
             'Shadow of the Giants 50K (USA)': -119.3528,
             'Vermont 50 Miles Ultra Run (USA)': -72.5940,
             'Quicksilver 50 km Endurance Run (USA)': -121.9390,
             'Bighorn Mountain Wild & Scenic 50km Trail Run (USA)': -107.2675,
             'Ohlone 50K Wilderness Run (USA)': -121.9390,
             'Miwok 100k Trail race (USA)': -122.6350,
             'Siskiyou Out Back 50 km Trail Run (USA)': -122.7150,
             'The Rut Mountain Runs (USA)': -111.0961,
             'Sylamore Trail 50k Run (USA)': -91.9444,
             'Tamalpa Headlands 50K (USA)': -122.5667,
             'Speedgoat 50k (USA)': -111.6533,
             'Moab Red Hot 55k (USA)': -109.5283,
             'McKenzie River 50 km Trail Run (USA)': -122.1200,
             'San Juan Solstice 50 Mile Run (USA)': -107.3133,
             'Chicago Lakefront Fall 50K (USA)': -87.6510,
             'Lake Sonoma 50 Mile Race (USA)': -122.8780,
             'The Bear 100 Mile Endurance Run (USA)': -111.8330,
             'Mount Cheaha 50K UltraMarathon Race (USA)': -85.8167,
             'Vermont 50 km Ultra Run (USA)': -72.5940,
             'Stone Mill 50 Mile Run (USA)': -77.0480,
             'Black Canyon Trail 100 Km Run (USA)': -112.7400,
             'Angeles Crest 100 Mile (USA)': -117.6250,
             'Ice Age Trail 50 km Run (USA)': -88.6004,
             'Umstead Endurance Run 100 Miles (USA)': -78.5900,
             'Tunnel Hill 50 Mile Race (USA)': -89.0430,
             'Catoctin 50k Trail Run (USA)': -77.4200,
             'Jed Smith Ultra Classic - 50 Km Race (USA)': -121.4064,
             'Highlands Sky 40M Trail Run (USA)': -79.4980,
             'Sunmart Texas Trail Endurance Run 50 Mile (USA)': -95.5500,
             'Noble Canyon 50k (USA)': -116.6010,
             'Hagg Lake Trail Runs 50K (USA)': -123.0050,
             'Endurance Challenge - New York Trail 50 Miles (USA)': -74.0020,
             'Terrapin Mountain 50k (USA)': -79.3530,
             'Massanutten Mountain Trails 100 Mile (USA)': -78.6100,
             'Mount Mitchell Challenge (USA)': -82.3170,
             'Le Grizz 50 Mile Ultramarathon (USA)': -114.2750,
             'Arkansas Traveller 100 (USA)': -92.7850,
             'Umstead Endurance Run 50 Miles (USA)': -78.5900,
             'Pineland Farms 50 km Trail Running (USA)': -70.3000,
             'Buckeye Trail 50k (USA)': -81.5990,
             'Endurance Challenge - Washington D.C. Trail 50 Miles (USA)': -74.0020,
             'Salem Lakeshore Frosty Fifty (USA)': -80.2700,
             'Marine Corps 50km Marathon Race (USA)': -77.0550,
             'Orcas Island 50k (USA)': -122.7900,
             'Endurance Challenge - Wisconsin Trail 50 km (USA)': -88.3380,
             'Holcomb Valley 33 Mile (USA)': -116.8000,
             'Mohican Trail 100 Mile (USA)': -82.2310,
             'Bighorn Mountain Wild & Scenic 50mi Trail Run (USA)': -107.2500,
             'Baker Lake 50K Ultra Trail Run (USA)': -121.7000,
             'Chippewa Moraine 50km Ultra Marathon (USA)': -91.9500,
             'Superior Spring 50 km Trail Race (USA)': -90.7500,
             'Trail Mix Race (USA)': -74.1500,
             'Capon Valley 50K Run (USA)': -78.3583,
             'Chicago Lakefront Spring 50K (USA)': -87.5750,
             'Hardrock Hundred Endurance Run (USA)': -107.6600,
             'Burning River 100 Mile Endurance Run (USA)': -81.5070}

In [6]:
# Create columns from latitude and longitude

um_df['latitude'] = um_df['Event name'].map(latitude)
um_df['longitude'] = um_df['Event name'].map(longitude)

In [7]:
um_df.head()

,Year of event,Event name,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete ID,...,Highest Elevation (feet),Elevation Gain (feet),Average state elevation (feet),Distance (miles),Hours Ran,mph,state_code,datetime,latitude,longitude
0,2018,Chuckanut 50K (USA),410,3:36:35,"*Folsom, CA",USA,1991,M,23,12058,...,1870.0,5000.0,1700.0,31.0,3.609722,8.587918,WA,2018-03-17,48.7033,-122.4786
1,2018,Chuckanut 50K (USA),410,3:40:57,"*Santa Fe, NM",USA,1986,M,23,12059,...,1870.0,5000.0,1700.0,31.0,3.682500,8.418194,WA,2018-03-17,48.7033,-122.4786
2,2018,Chuckanut 50K (USA),410,3:47:43,"*San Francisco, CA",IRL,1987,M,23,12060,...,1870.0,5000.0,1700.0,31.0,3.795278,8.168045,WA,2018-03-17,48.7033,-122.4786
3,2018,Chuckanut 50K (USA),410,3:48:13,"*Ashland, OR",USA,1988,M,23,12061,...,1870.0,5000.0,1700.0,31.0,3.803611,8.150150,WA,2018-03-17,48.7033,-122.4786
4,2018,Chuckanut 50K (USA),410,3:50:55,"*Bend, OR",USA,1981,M,35,12062,...,1870.0,5000.0,1700.0,31.0,3.848611,8.054854,WA,2018-03-17,48.7033,-122.4786

In [8]:
# filter to the 50 km races.  They hold the top 50 races out of the top 100.

fifty_um_df = um_df[um_df['Distance (miles)'] == 31.0]

In [9]:
fifty_um_df = fifty_um_df[fifty_um_df['true age'] < 100]

In [10]:
fifty_um_df['Athlete ID'].nunique()

80266

In [11]:
fifty_um_df[fifty_um_df["Athlete gender"] == 'M'].nunique()

Year of event                        41
Event name                           50
Event number of finishers           367
Athlete performance               23141
Athlete club                       9283
Athlete country                      72
Athlete year of birth                92
Athlete gender                        1
Athlete age category                 13
Athlete ID                        51954
true age                             81
State                                26
Highest Elevation (feet)             34
Elevation Gain (feet)                34
Average state elevation (feet)       23
Distance (miles)                      1
Hours Ran                         23141
mph                               23141
state_code                           25
datetime                            862
latitude                             50
longitude                            49
dtype: int64

In [12]:
fifty_um_df[fifty_um_df["Athlete gender"] == 'F'].nunique()

Year of event                        41
Event name                           50
Event number of finishers           365
Athlete performance               18647
Athlete club                       5984
Athlete country                      57
Athlete year of birth                86
Athlete gender                        1
Athlete age category                 12
Athlete ID                        28327
true age                             72
State                                26
Highest Elevation (feet)             34
Elevation Gain (feet)                34
Average state elevation (feet)       23
Distance (miles)                      1
Hours Ran                         18647
mph                               18647
state_code                           25
datetime                            860
latitude                             50
longitude                            49
dtype: int64

In [13]:

# Data hosts top 50, 50km races in the United States from 1982 to 2022.
# There are 59,387 (28,327 unique) females running and 130,223 (51,954 unique) males running.
# There are 80,266 individual racers in the data.
# Age ranges from 8 - 90 years
# Data to Focus on for features: Athlete Gender, Athlete Age Category, Average State Elevation, (datetime possibly).
# Target data: mph (average race pace)

In [14]:
fifty_um_df['Athlete age category'].unique()

array(['23', '35', '45', '40', 'U23', '50', '55', '60', '65', '70', '75',
       '80', '85'], dtype=object)

In [15]:
# Now that our data has been filtered we are going to save the data.
fifty_um_df.to_csv('../Data/top_50_50km.csv')